[tool.coverage.run]
source = ["PyRoute/"]


[tool.mutmut]
paths_to_mutate = ["PyRoute/"]
tests_dir = ["Tests/"]
also_copy = ["Tests/", "pytest.ini"]
runner = "pytest -x -p no:randomly -k testStarList"
max_stack_depth = 8
